#version 430

layout(local_size_x = 256) in;
layout(std430, binding = 0) buffer Buf { float data[]; };

uniform uint elementCount;

void main() {
    uint i =
	    gl_GlobalInvocationID.x +
	    gl_GlobalInvocationID.y * gl_NumWorkGroups.x * gl_WorkGroupSize.x +
	    gl_GlobalInvocationID.z * gl_NumWorkGroups.x * gl_WorkGroupSize.x *
	                             gl_NumWorkGroups.y * gl_WorkGroupSize.y;
    if (i >= elementCount)
        return;
        
    data[i] = 0.0;
}
