spring.application.name=pendulum-nn-server
spring.application.version=0.1
spring.application.build=@build.timestamp@
spring.application.shared-version=@git.branch@#@git.commit.id.abbrev@

# server & session config
server.port=4356
server.shutdown=graceful
server.servlet.session.persistent=false

# nginx proxy
server.forward-headers-strategy=framework

# hide stacktrace in response if error
server.error.include-stacktrace=never
server.error.include-message=never
server.error.include-binding-errors=never

# disable spring logging
logging.level.org.springframework.context.support.PostProcessorRegistrationDelegate=ERROR
logging.level.org.springframework.aop.framework.CglibAopProxy=ERROR
logging.level.org.springframework.web.multipart=OFF
#logging.level.org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/]=OFF


